services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
