services:
  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
